# Generated by Django 3.2 on 2023-02-25 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0018_tournamentsplitelimination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournaments', models.ManyToManyField(related_name='tournaments_in_group', to='tournament.Tournament')),
                ('users', models.ManyToManyField(related_name='users_in_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
