# Generated by Django 3.2 on 2023-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgroup',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentgroup',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
