# Generated by Django 3.2 on 2023-02-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournamentelimination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstructure',
            name='bounty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
