# Generated by Django 3.2 on 2023-02-08 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournamentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentelimination',
            name='eliminated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
