# Generated by Django 3.2 on 2023-02-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournamentelimination_eliminated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('placement', models.IntegerField()),
                ('placement_earnings', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bounty_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rebuys', models.IntegerField()),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_earnings', models.DecimalField(decimal_places=2, max_digits=9)),
                ('eliminations', models.ManyToManyField(to='tournament.TournamentElimination')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
