# Generated by Django 3.2 on 2023-02-11 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0009_tournamentplayerresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='num_rebuys',
        ),
        migrations.RemoveField(
            model_name='tournamentplayerresult',
            name='rebuys',
        ),
        migrations.CreateModel(
            name='TournamentRebuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournamentplayerresult',
            name='rebuys',
            field=models.ManyToManyField(to='tournament.TournamentRebuy'),
        ),
    ]
