# Generated by Django 3.2 on 2023-02-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20230211_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentelimination',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='tournamentelimination',
            name='eliminatee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eliminatee', to='tournament.tournamentplayer'),
        ),
        migrations.AlterField(
            model_name='tournamentelimination',
            name='eliminator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eliminator', to='tournament.tournamentplayer'),
        ),
    ]
