# Generated by Django 3.2 on 2023-02-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_auto_20230212_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentrebuy',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='tournament.tournamentplayer'),
        ),
    ]
