# Generated by Django 3.2 on 2023-02-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_tournamentrebuy_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayerresult',
            name='placement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
