# Generated by Django 3.2 on 2023-02-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20230212_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayerresult',
            name='is_backfill',
            field=models.BooleanField(default=False),
        ),
    ]
