# Generated by Django 3.2 on 2023-02-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_tournamentplayerresult_is_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentplayerresult',
            name='eliminations',
        ),
        migrations.RemoveField(
            model_name='tournamentplayerresult',
            name='rebuys',
        ),
    ]
