# Generated by Django 3.2 on 2023-02-23 01:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebuild_hash', models.CharField(max_length=255)),
                ('tournaments_played', models.IntegerField(blank=True, default=0, null=True)),
                ('gross_earnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=9, null=True)),
                ('net_earnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=9, null=True)),
                ('losses', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=9, null=True)),
                ('eliminations', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=9, null=True)),
                ('rebuys', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
