# Generated by Django 3.2 on 2023-02-23 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttotals',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 23, 16, 0, 6, 741201, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
