# Generated by Django 3.2 on 2023-02-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_analytics', '0002_tournamenttotals_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenttotals',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
